### ISSUE TITLE
Support for `terraform plan`

### ISSUE THREAD

**Issue by mdb** [ljfranklin/terraform-resource#10]
Thanks so much for the work here! Has any consideration been given to `terraform plan` functionality? For example, my team would like to be able to assess `terraform plan` output before executing `terraform apply`. 

I'm somewhat naive -- so apologies if I'm off base -- but I'm imagining something akin to the following:
- support for `action: plan` functionality that makes Terraform's `tfplan` available as Concourse resource output
- support to allow `terraform apply` to accept the `tfplan` resulting from an `action: plan` as Concourse resource input

**Comment by ljfranklin** [comment]
@mdb an interesting idea, but I'm not sure about passing along the `tfplan` as an output. For a `put` in Concourse to output something, it needs to create a new version. A new version signifies something changed in the IaaS, so it feels off to create a new version for a plan. It would also require changing the subsequent `get` to return a plan file instead of a `metadata` file, also not great.

That said, I'm not necessarily opposed to a `put.params.plan_only: true` or something like that. This `put` could print the plan to the UI, but wouldn't output any new versions. Your "plan" job could be followed by a manually triggered "apply" job which would perform a normal terraform `put`. This doesn't provide quite the level of confidence that executing the exact plan file would, but should be close enough unless you have a lot of out-of-band changes going on.

**Comment by mdb** [comment]
@ljfranklin I see. I do also like your `put.params.plan_only: true` idea. Essentially, this is what my team's custom Terraform jobs/tasks do, though we'd love to leverage your `terraform-resource` rather than maintain our own code.

**Comment by Seraf** [comment]
Hello, that's something we are also trying to achieve.

The ideal should be to have a pipeline running a plan, then exposing it, waiting an approval, then running the apply.

**Comment by Seraf** [comment]
Hello @ljfranklin

We (my company) need this feature to use the terraform resource safely. Do you need some help ? Maybe we can check to make a PR for this ?

Thanks

**Comment by ljfranklin** [comment]
@Seraf A PR would be great!

I talked with the Concourse team last week, sounds like the easiest way to implement this would be to add a field in the `put` version indicating that this version is a "plan" version, e.g. `version: { "env_name": "...", "last_modified": "...", "plan": true }`. The subsequent `get` then knows to looks for `${env_name}.tfplan` or similar in S3 and fetch it down. A second `put` then takes a path to that file as a `put` param. Probably need to delete the plan file from S3 after the next successful `put` as well. I think this should all work fine with the new versioning changes proposed in https://github.com/concourse/concourse/issues/534 as well.

So your pipeline config would look something like this (feel free to change names):

```yaml
 - name: terraform-plan
   plan:
      - put: terraform
        params:
          env_name: staging
          plan_only: true
          vars:
            subnet_cidr: 10.0.1.0/24

- name: terraform-apply
  plan:
      - get: terraform
        trigger: false
        passed: [terraform-plan]
      - put: terraform
        params:
          env_name: staging
          plan_file: terraform/plan # fixed name is probably easier than glob
          vars:
            subnet_cidr: 10.0.1.0/24
```

@Seraf Let me know if you have any questions or if something looks amiss.
