### ISSUE TITLE
S3 bucket format from apply cannot destroy

### ISSUE THREAD

**Issue by h4xnoodle** [ljfranklin/terraform-resource#103]
I have the following source config, `put` and `put` for destroy. 

Resources:
```
  - name: terraform
    type: terraform
    source:
      backend_type: s3
      backend_config:
        bucket: <bucket>
        key: terraform/terraform.tfstate
        region: ...
        access_key: ...
        secret_key: ...
```
Within a job:
```
    - put: terraform
      params:
        env_name: lifecycle
        terraform_source: ...
        vars:
          prefix: "lifecycle"
          ...
    - do:
      - task: test
        file: ...
        params:
          ...
      ensure:
        put: terraform
        params:
          action: destroy
          env_name: lifecycle
          terraform_source: ...
        get_params:
          action: destroy
```

In my S3 bucket, I see the following path for the terraform state file: `<bucket>/env:/lifecycle/terraform/terraform.state`. From other pipelines I've setup it usually ends up as `<bucket>/terraform/terraform.state`. The only correlation I can see is the `env_name` which I have for both `put`s. Is the `prefix` related here? Perhaps I need the prefix on both?

When I attempt to `put` for destroy, the task doesn't seem to be able to find the file, as the `put` displays terraform asking for inputs to destroy.
