### ISSUE TITLE
Usage of custom plugin (wavefront) is not recognized my the concourse ci resource

### ISSUE THREAD

**Issue by nischit7** [ljfranklin/terraform-resource#108]
I am using wavefront terraform provider. Unfortunately, its not available in public registry. Hence I have to load as custom plugin.

My service git folder looks as below -

```
service-git:
     terraform
         - wavefront
              main.tf
              - .terraform.d
                     - plugins
                          terraform-provider-wavefront_v2.1.1
```

My Concourse CI plan -
```
resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: 0.12.23

resources:
  - name: service-git
    type: git
    icon: git
    source:
      uri: my.git
      branch: master
      private_key: .....

  - name: tf-service-us-east-1-dev
    type: terraform
    source:
      backend_type: s3
      backend_config:
        bucket: some-bucket
        key: some-key
        workspace_key_prefix: some-key-prefix
        region: us-east-1
        access_key: my-access-key
        secret_key: my-secret-key
        session_name: terraform-dev-backend-config
      env:
        AWS_ACCESS_KEY_ID: my-access-key
        AWS_SECRET_ACCESS_KEY: my-secret-key
        AWS_DEFAULT_REGION: us-east-1

      - put: tf-plan-us-east-1-dev
        resource: tf-service-us-east-1-dev
        attempts: 2
        params:
          env_name: dev
          terraform_source: service-git/terraform/wavefront
          plan_only: true
```

My wavefront terraform (main.tf) looks as below -
```
provider "wavefront" {
  address = "something.wavefront.com"
  token = "mytoken"
  version = "v2.1.1"
}

resource "wavefront_alert" "test_alert" {
  name = "Terraform Test Alert"
  target = "test@example.com"
  condition = "100-ts(\"cpu.usage_idle\", environment=flamingo-int and cpu=cpu-total and service=game-service) > 80"
  display_expression = "100-ts(\"cpu.usage_idle\", environment=flamingo-int and cpu=cpu-total and service=game-service)"
  minutes = 5
  resolve_after_minutes = 5
  severity = "WARN"
  tags = [
    "terraform",
    "flamingo"
  ]
}
```

As per the documentation if we specify "plugin_dir", 
```
The path (relative to your terraform_source) of the directory containing plugin binaries. This overrides the default plugin directory and Terraform will not automatically fetch built-in plugins if this option is used. To preserve the automatic fetching of plugins, omit plugin_dir and place third-party plugins in ${terraform_source}/terraform.d/plugins. See https://www.terraform.io/docs/configuration/providers.html#third-party-plugins for more information.
```

If you note carefully...
terraform_source = service-git/terraform/wavefront

and the custom plugin is at service-git/terraform/wavefront/.terraform.d/plugins/terraform-provider-wavefront_v2.1.1 (I also tried with folder service-git/terraform/wavefront/`terraform.d`/plugins)

By using the above configuration, I get Concourse CI error as below -

```
terraform init command failed.
Error: exit status 1
Output: 
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...

Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* wavefront (v2.1.1)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/linux_amd64


Error: missing provider "wavefront"

```

I then altered the Concourse CI plan to use "plugin_dir":

      - put: tf-plan-us-east-1-dev
        resource: tf-service-us-east-1-dev
        attempts: 2
        params:
          env_name: dev
          terraform_source: service-git/terraform/wavefront
          plan_only: true
          plugin_dir: .terraform.d/plugins

As expected, it failed as it could not find AWS specific provider.

```
▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ Terraform Plan ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼

Error: Could not satisfy plugin requirements


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".



Error: provider.aws: new or changed plugin executable


▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Plan ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
Failed To Run Terraform Plan!
Plan Error: Failed to run Terraform command: exit status 1

```

Can you pls let me know what could be the issue?

**Comment by ljfranklin** [comment]
Can you try removing `params.plugin_dir` and change the plugin filename in your git repo to `terraform.d/plugins/linux_amd64/terraform-provider-wavefront_v2.1.1`? Note the architecture directory and that there's no `.` in front of `terraform.d`, the [plugin docs](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations) show that when storing plugins in your VCS it doesn't want the leading dot.

**Comment by nischit7** [comment]
Before I put forward my observation let me point out, I did try your suggestion just now.

My revised git stucture is below -
```
service-git:
     terraform
         - wavefront
              main.tf
              - .terraform.d
                     - plugins
                          - darwin_amd64
                                 terraform-provider-wavefront_v2.1.1

```

My revised Concource CI plan is below (not pasting the whole content again)
```
      - put: tf-plan-us-east-1-dev
        resource: tf-service-us-east-1-dev
        attempts: 2
        params:
          env_name: dev
          terraform_source: service-git/terraform/wavefront
          plan_only: true
```

The error is same, unable to find the provider.
```
Error: exit status 1
Output: 
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...

Provider "wavefront" not available for installation.

A provider named "wavefront" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name
```

Now coming to my observation from official terraform documentation for third party plugins.
Pls refer https://www.terraform.io/docs/configuration/providers.html#third-party-plugins.

```
Windows               | %APPDATA%\terraform.d\plugins
All other systems | ~/.terraform.d/plugins
```

There is a leading dot. Now I have a macbook.

Before going down the path of using this concourse, I did try locally on my laptop using terraform CLI.
Before trying all these I did test successfully on my mac.

```
**nischit$ wavefront %** ls -ltr ~/.terraform.d/plugins 
-rwxrwxrwx@ 1 nischit  user  29394768 Mar 25 15:20 terraform-provider-wavefront_v2.1.1

**nischit$ wavefront %** pwd                          
/my-repo/terraform/wavefront

**nischit$ wavefront %** terraform init

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**nischit$ wavefront %** 

**nischit$ wavefront %** terraform apply -auto-approve
wavefront_alert.test_alert: Creating...
wavefront_alert.test_alert: Creation complete after 1s [id=1585277573916]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by ljfranklin** [comment]
Please try it without the leading dot. Check [this link](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations) I posted, if the plugins are in your home directory it has a leading dot but if it's in your working directory it's `terraform.d` without the dot. There's also [code](https://github.com/ljfranklin/terraform-resource/blob/b05ddccf8538d0ebbd7efa9dc6660b30ab984c04/src/terraform-resource/terraform/action.go#L54-L64) in the resource to handle symlinking to the plugin directory with that name.

**Comment by ljfranklin** [comment]
Also unless your Concourse is running on a mac mini or something, you need plugins compiled for linux and your directory should say `linux_amd64`.

**Comment by nischit7** [comment]
I am stupid.... but sometimes I can be even more stupid.
If someone like me has come in search for an answer, read the comment made by @ljfranklin  closely.

To give more information .....
```
service-git:
     terraform
         - wavefront
              main.tf
              - terraform.d
                     - plugins
                          - linux_amd64
                                 terraform-provider-wavefront_v2.1.1
```
Sometimes a custom plugin might have to be recompiled to make golang work with alpine.
A sample concourse ci plan that worked for me is below -
```
       - name: terraform
          type: terraform
          source:
             backend_type: s3

        - put: terraform-pan
          resource: terraform
          attempts: 2
          params:
             env_name: dev
             terraform_source: service-git/terraform/wavefront
             plan_only: true
          vars:
           ...

        - put: terraform-apply
           resource: terraform
           attempts: 2
           params:
              env_name: dev
              terraform_source: service-git/terraform/wavefront
              plan_run: true
          vars:
           ...

```
