### ISSUE TITLE
Add option to fail on diff

### ISSUE THREAD

**Issue by bartlettt** [ljfranklin/terraform-resource#116]
Could you add an option to fail a plan if a diff is detected. The parameter could be something like `fail_on_diff`. That way I can have concourse automatically detect if any terraform drift has occurred. This is necessary to detect and rectify manual changes.

I imagined the concourse config would look something like:
```
jobs:
  - name: terraform-detect-drift
    serial: true
    plan:
      - get: at-midnight
        trigger: true
      - get: git-source
      - put: terraform
        params:
          terraform_source: git-source
          plan_only: true
          fail_on_diff: true

    on_failure:
      put: slack-alert
      params:
        channel: "#drift"
        text: |
          Drift detected for $BUILD_PIPELINE_NAME
          https://concourse.example.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
          <@UQJV487S5>
        username: Concourse
        silent: false
```
