### ISSUE TITLE
Provide example Concourse pipeline to build Terraform + Resource from source

### ISSUE THREAD

**Issue by ljfranklin** [ljfranklin/terraform-resource#12]
As new features are added to Terraform so quickly, some users would like to use new Terraform features with this resource before the feature has been officially released. A set of re-usable Concourse tasks and pipeline config would allow teams to build terraform from source from a given git ref and push a "one-off" docker image for the resource containing that dev build. The task should optionally take the Terraform git ref as well as the Resource git ref, otherwise default to building from master.

**Comment by Seraf** [comment]
Ah, perfect !

I was going to open an issue to ask you if it could be possible to tag terraform resource release with the terraform version.
There's actually a bug in the last versions : https://github.com/hashicorp/terraform/issues/9289 and we need to stick to the 0.7.3 until this bug is fixed.

We setup a pipeline on our internal concourse in order to work on the plan feature. We had to modify the region parameter on your pipeline as we don't use the us-east-1 by default.
We also had a problem building the container with the current dockerfile : wget wasn't able to get terraform through https, there were an error on getting the certificate, we had to install openssl to get it working. I don't understand why as it seems to work on your pipeline ...

So, to avoid noise in our master that differ from your repo, I put everything in a CI branch that is pulled as a resource to trigger all the docker stuff, and we use another branch to build the terraform resource.

Here is the changes we have to do to setup the pipeline: https://github.com/cycloidio/terraform-resource/commits/ci

**Comment by ljfranklin** [comment]
> tag terraform resource release with the terraform version

@Seraf yep, I can do that. Figured that would be needed that eventually, just waiting for someone to ask :)

For the docker issue, my `dev` Dockerfile was a bit out of sync. I'm updating it now, you should be able to use `ljfranklin/terraform-resource:dev` to download terraform going forward.

**Comment by zachgersh** [comment]
hey @ljfranklin I actually wanted to take a different approach which would mean you wouldn't have to have a pipeline hanging around. Why can't the source configuration take something like a:

`override_terraform_binary_location: /some/path/in/container`

This would give users a bunch of flexibility as they could either use the one you ship by default or swap the binary out for one of their choosing. Are there drawbacks to this that I am not seeing?

I can totally do the PR for this as well.

**Comment by ljfranklin** [comment]
@zachgersh that was the original request from @wendorf that prompted this. I have a couple concerns with the binary path approach.

When using the path approach you need to fetch the binary in from somewhere. So you add an S3 resource to the pipeline or create a task that builds from source and requires a Golang docker image. Once you want to switch back to latest, you then need to remove all that stuff.

Another is actually building terraform from source properly. While Golang makes it about as easy as possible to build from source, there are still some gotchas. Something I hit a while back, let's say you build terraform from source on your linux workstation, the binary runs fine locally, but throws "No such file or directory" when you run the binary in the docker container. Turns out Golang will dynamically compile the binary by default if the target system is the same as your current system, so the binary linked against glibc and the alpine docker image doesn't have that. Providing re-usable tasks that know how to build from source avoids all this.

Overall I think the docker approach just ends up looking nicer as you only need to change the `resource_type.source.tag` to swap between versions:

```yaml
# latest
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

# pinned to a given terraform version
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.7.3

# your own custom version
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: zachgersh/terraform-resource
    tag: pr-azure-lbs
```
