### ISSUE TITLE
output_planfile: state has no output for key plan_content_json

### ISSUE THREAD

**Issue by talset** [ljfranklin/terraform-resource#121]
I tried to get the plan file locally with the following config:

```
resources:
  - name: tfstate
    type: terraform
    source:
      backend_config:
         path: "terraform.tfstate"
      backend_type: local
      env:
        AWS_ACCESS_KEY_ID: ((aws.access_key))
        AWS_DEFAULT_REGION: eu-west-1
        AWS_SECRET_ACCESS_KEY: ((aws.secret_key))
      env_name: test

     ...

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: 0.12.26-b11328e
jobs:
  - name: terraform-plan
    plan:
      - do:
          - get: git_terraform
            trigger: true
          - put: tfstate
            params:
              plan_only: true
              terraform_source: git_terraform/
            get_params:
              output_planfile: true
```

But after the end of the task with `Successfully Ran Terraform Plan!`
the put output say `2020/06/08 12:24:51 state has no output for key plan_content_json`
