### ISSUE TITLE
Terraform destroy fails when trying to delete default workspace

### ISSUE THREAD

**Issue by stuart-c-moore** [ljfranklin/terraform-resource#125]
When using an `env_name` of `default`, the terraform destroy action fails when trying to delete the workspace after the destroy.

Given the following concourse code:

```
- name: terraform-charon
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: ((google_project))
      prefix: charon
      credentials: ((google_credentials))
    env_name: default

- name: terraform-destroy-charon
  serial_groups: [terraform-charon]
  disable_manual_trigger: ((terraform_destroy_disable_manual_trigger))
  plan:
  - get: git_charon
    trigger: ((terraform_destroy))
    passed: [terraform-apply-charon]
  - get: git_core
    trigger: ((terraform_destroy))
    passed: [terraform-apply-charon]
  - get: git_terraform_modules
    trigger: ((terraform_destroy))
    passed: [terraform-plan-charon]
  - put: terraform-charon
    params:
      action: destroy
      terraform_source: git_charon/charon/terraform
      env:
        GOOGLE_CREDENTIALS: ((google_credentials))
      vars:
        <<: *terraform-params-charon
  <<: *slack-alert
```

This successfully destroys the resources, but then the concourse job fails after terraform fails to delete the default workspace:

```
<snip>
Destroy complete! Resources: 14 destroyed.
▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Destroy ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
2020/08/19 11:44:54 Error running `workspace delete`: exit status 1, Output: Workspace "default" is your active workspace.

You cannot delete the currently active workspace. Please switch
to another workspace and try again.
```

Running the commands manually after intercepting the failed concourse job:

```
bash-5.0# terraform state list
bash-5.0# terraform workspace list
* default

bash-5.0# terraform workspace delete -force default
Workspace "default" is your active workspace.

You cannot delete the currently active workspace. Please switch
to another workspace and try again.
```

Could the resource be modified to skip attempting to destroy the workspace with either some flag, or if the env_name is set to default?
