### ISSUE TITLE
May I ask where do I find storage_access_key and storage_secret_key

### ISSUE THREAD

**Issue by JizongL** [ljfranklin/terraform-resource#134]
in the backend config, it's using 

```
 - name: terraform
    type: terraform
    source:
      backend_type: s3
      env_name: dev
      backend_config:
        bucket: neighborly-bucket
        key: terraform.tfstate
        region: eu-west-1
        access_key: ((storage_access_key))
        secret_key: ((storage_secret_key))
      env:
        AWS_ACCESS_KEY_ID: ((environment_access_key))
        AWS_SECRET_ACCESS_KEY: ((environment_secret_key))
```
may I ask where do you get them? so far I only can find the environment access key and secret from my aws account credential.
