### ISSUE TITLE
Lack of output/troubleshooting help

### ISSUE THREAD

**Issue by pezhore** [ljfranklin/terraform-resource#138]
I'm trying to figure out what I'm missing - no matter what I try, I can't seem to get reasonable output from the terraform resource in concourse. Success or failures don't seem to provide much output in the UI/console:

![image](https://user-images.githubusercontent.com/7430984/101821321-6d479500-3aed-11eb-9c06-9542bea853f9.png)

This makes troubleshooting particularly difficult and I'm open to suggestions on how to fix this.

Pipeline: 

```yaml
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: samcontesse/gitlab-merge-request-resource
- name: terraform
  type: docker-image
  source:
    repository: harbor.example.local:443/custom-certs/tf-docker
    tag: latest
    ca_certs:
    - domain: harbor.example.local:443
      cert: ((harbor.cert))

resources:
  - name: gated-vm-deploy
    type: merge-request
    icon: gitlab
    check_every: 1s
    source:
      uri: https://gitlab.example.local/pezhore/gated-vm-deploy.git
      private_token: ((gitlab.access_token))
      insecure: true
  - name: terraform
    type: terraform
    icon: terraform
    source:
      env_name: staging
      backend_type: s3
      backend_config:
        bucket: range-infra
        access_key: ((terraform.backend_access_key))
        secret_key: ((terraform.backend_secret_key))
        endpoint: https://minio.example.local
        key: gated-vm-deploy/terraform.tfstate
        region: main
        force_path_style: true
        skip_credentials_validation: true
        skip_metadata_api_check: true
        skip_region_validation: true
      env:
        VSPHERE_USER: ((terraform.vsphere_user))
        VSPHERE_PASSWORD: ((terraform.vsphere_password))
        VSPHERE_SERVER: vcenter.example.local
        TF_LOG: DEBUG
      vars:
        num_cpus: 2

jobs:
- name: merge-request
  plan:
  - get: gated-vm-deploy
    trigger: true
  - put: gated-vm-deploy
    params:
      repository: gated-vm-deploy
      status: running
  - put: terraform
    params:
      env_name: staging
      terraform_source: gated-vm-deploy/terraform
      plan_only: true
    get_params:
      output_planfile: true
  on_failure:
    put: gated-vm-deploy
    params:
      repository: gated-vm-deploy
      status: failed
  on_success:
    put: gated-vm-deploy
    params:
      repository: gated-vm-deploy
      status: success
      labels: ['unit-test', 'stage']
      comment:
        file: terraform/plan.json
        text: |
          plan output:
          $FILE_CONTENT
- name: terraform-apply
  plan:
  - get: gated-vm-deploy
    trigger: false
    passed: [merge-request]
  - get: terraform
    trigger: false
    passed: [merge-request]
  - put: terraform
    params:
      env_name: staging
      terraform_source: gated-vm-deploy/terraform
      plan_run: true
```
