### ISSUE TITLE
import_files is not used when plan_only is set

### ISSUE THREAD

**Issue by fenech** [ljfranklin/terraform-resource#146]
I would like to ensure that running `apply` doesn't lead to any data loss for an existing repo, so I added a file `github.yml`:

```yaml
github_repository.my_repo: my-repo
```

and in my pipeline I have configured:

```yaml
  - name: plan-terraform-github
    public: true
    plan:
      - get: repo
        trigger: true
      - put: terraform-github
        params:
          terraform_source: repo/terraform/github
          plan_only: true
          import_files:
            - repo/terraform/imports/github.yml
```

but when I run the job, it says that the a new repo will be added, and there is no sign of any import having taken place.

Is this the expected behaviour? If so, how can I make sure that it is safe to run the `apply`?
