### ISSUE TITLE
'workspaces not supported' error

### ISSUE THREAD

**Issue by grzleadams** [ljfranklin/terraform-resource#148]
I use an Artifactory backend and when I specify source.env_name or put.params.env_name, I get a `workspaces not supported` error (which might be fine, because they're not for that backend). But I can't leave them (or the other two options) out because one of the four is required. Using 'default' (which I've seen suggested elsewhere) doesn't seem to help either. 

Sanitized backend resource:
```
  - name: terraform
    type: terraform
    source:
      env_name: default
      env:
        TF_LOG: TRACE
      backend_type: artifactory
      backend_config:
        username: ((artifactory-user))
        password: ((artifactory-token))
        url: ((artifactory-url))
        repo: "terraform-local"
        subpath: "production"
```
Thanks for any input you can provide!

**Comment by ljfranklin** [comment]
Huh, didn't realize some backends don't support workspaces. Looks like you already have debug logging on, which Terraform command is actually failing? I'm guessing `terraform workspaces list` but please confirm. If that is the issue you can try adding a line [here](https://github.com/ljfranklin/terraform-resource/blob/0058e111967ee4efcc4fcf1bf9b09b5fce9b682a/src/terraform-resource/terraform/client.go#L500) to return `[]string{"default"}` rather than an error if the output contains `workspaces not supported`. Instructions to build your own image to test your changes are [here](https://github.com/ljfranklin/terraform-resource/blob/master/DEVELOPMENT.md#testing-your-changes-in-concourse).

**Comment by grzleadams** [comment]
Yeah, it's `terraform workspaces list` that's failing. I ended up switching to a pg backend for the sake of progress but am now encountering a whole other set of issues with resource imports in my plan, so it might be a bit before I get to test that solution out. We can close this if you want, or keep it open until I'm able to verify that it works, whatever you want to do.

**Comment by laurenty** [comment]
Having the same issue when trying to use Terraform Cloud for backend

**Comment by ljfranklin** [comment]
Looks like the Terraform remote (Cloud) backend does support workspaces, but it returns "not supported" if the `prefix` key is [not provided](https://github.com/hashicorp/terraform/blob/960f736bc2170e3aad57d2d529d9a315f5a1e741/internal/backend/remote/backend.go#L519-L521). @laurenty can you try adding the [workspaces.prefix](https://www.terraform.io/docs/language/settings/backends/remote.html#basic-configuration) key to your `backend_config`?

**Comment by laurenty** [comment]
@ljfranklin It didn't work. I already had a name configured for the workspace, so adding prefix resulted in the following error.
```
2021/08/23 01:07:59 terraform init command failed.
Error: exit status 1
Output: 
Initializing the backend...

Error: Invalid workspaces configuration

  on resource_backend_override.tf line 2, in terraform:
   2: 		backend "remote" {}

Only one of workspace "name" or "prefix" is allowed.
```
Here's the basic config I've been using for testing
```
---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.13.5

resources:
- name: source-repo
  type: git
  icon: github
  source:
    uri: https://github.com/<some test repo>.git
    branch: main
  check_every: 1h

- name: core-terraform
  type: terraform
  icon: terraform
  source:
    env_name: test
    backend_type: remote
    backend_config:
      hostname: app.terraform.io
      organization: <org-name>
      token: <token>
      workspaces:
        prefix: dev
        name: concourse-test

jobs:
- name: apply-terraform
  plan:
  - get: source-repo
    trigger: true
  - put: core-terraform
    params:
      plan_only: true
      terraform_source: source-repo
```
I know that both TF and TFC have workspaces, but they are slightly different concepts.
Per their docs (https://www.terraform.io/docs/cloud/workspaces/index.html)
> Note: Terraform Cloud and Terraform CLI both have features called "workspaces," but they're slightly different. CLI workspaces are alternate state files in the same working directory; they're a convenience feature for using one configuration to manage multiple similar groups of resources.

**Comment by ljfranklin** [comment]
> Terraform Cloud and Terraform CLI both have features called "workspaces," but they're slightly different

Right, but the Terraform Cloud backend does support the CLI concept of workspaces, i.e. store the statefile remotely.

It should work if you drop `workspaces.name` and change `source.env_name: test` to `source.env_name: concourse-test`. Under the hood the terraform-resource uses the env_name to do operations like `terraform workspace select $env_name`. If this is a new environment you should be fine, but if `concourse-test` already exists you'll have to migrate its statefile under the `dev` prefix.

**Comment by laurenty** [comment]
Hi @ljfranklin ,
That did not work either. This is the error I got this time:
```
2021/08/23 15:39:45 terraform init command failed.
Error: exit status 1
Output: 
Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: No existing workspaces.

Use the "terraform workspace" command to create and select a new workspace.
If the backend already contains existing workspaces, you may need to update
the backend configuration.
```
Pipeline was:
```
resources:
- name: source-repo
  type: git
  icon: github
  source:
    uri: https://github.com/<some-repo>.git
    branch: main
  check_every: 1h

- name: core-terraform
  type: terraform
  icon: terraform
  source:
    env_name: concourse-test
    backend_type: remote
    backend_config:
      hostname: app.terraform.io
      organization: <org-name>
      token: <token>
      workspaces:
        prefix: dev

jobs:
- name: apply-terraform
  plan:
  - get: source-repo
    trigger: true
  - put: core-terraform
    params:
      plan_only: true
      terraform_source: source-repo
```
Looking at the files generated on the container for the `put` step I see that `resource_backend_config.json` contains the following:
```
{"hostname":"app.terraform.io","organization":"<org-name>","token":"<token>","workspaces":{"prefix":"dev"}}
```
and `resource_backend_override.tf`:
```
terraform {
	backend "remote" {}
}
``` 
which might explain why it's throwing an error. I'll dig in the code and will let you know what I find.
