### ISSUE TITLE
Something strange since resource bump to terraform 0.15.0

### ISSUE THREAD

**Issue by jppitout** [ljfranklin/terraform-resource#151]
IaaS: Azure
Workspaces: Yes
Terraform vestions: 0.11.14

Since the resource got bumped it seems either this resource is ignoring the `env_name: prod` parameter or the resource type is ignoring the `tag: "0.11.14"` parameter.

Even though both above parameters are set we are seeing a newly created terraform.tfstate file in our Azure blob storage container (i.e. instead of per workspace tfstate files e.g. terraform.tfstateenv:prod) and it is populated with the below despite the above tag and env_name being set:
```
{
  "version": 4,
  "terraform_version": "0.15.0",
  "serial": 0,
  "lineage": "5cd1a576-9c56-ac9b-ed19-7484f7266fb4",
  "outputs": {},
  "resources": []
}
```
Now we are seeing these errors in our pipeline:
```Error: 
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.15.0'

A newer version of Terraform is required to make changes to the current
workspace.
```
But it is looking at a tfstate file that shouldn't even exist. 
Not sure why or how this tfstate file is being created/referenced but the issue started shortly after this commit: https://github.com/ljfranklin/terraform-resource/commit/b59eb92c040a43983ec758fbbb4409f744f8afb5  I don't see any breaking changes here so really not sure...

Example code:
```
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: "0.11.14"

resources:
- name: infrastructure
  icon: terraform
  type: terraform
  source:
    env_name: ((env))
    backend_type: azurerm
    backend_config:
      resource_group_name: ((pipeline_resource_group_name))
      storage_account_name: ((pipeline_storage_account_name))
      container_name: ((pipeline_tfstate_container_name))
      key: terraform.tfstate
    env:
      ARM_SUBSCRIPTION_ID: ######
      ARM_CLIENT_ID: ######
      ARM_CLIENT_SECRET: ######
      ARM_TENANT_ID: ######
```
Any help would be appreciated.
