### ISSUE TITLE
How to reference `plan.json`

### ISSUE THREAD

**Issue by nathanshelly** [ljfranklin/terraform-resource#156]
Hi, first off thanks for your fantastic concourse resource!

I'm trying to have a job that alerts when there's a diff between the terraform configuration and the current repo configuration state as in [#116](https://github.com/ljfranklin/terraform-resource/issues/116). Unfortunately I'm having trouble referencing the `plan.json` file that's supposed to be created.

Based on the documentation and [this test code](https://github.com/ljfranklin/terraform-resource/blob/master/src/terraform-resource/in/in_plan_test.go#L269-L273) I'd expect the `plan.json` file to be generated at the same location as the `terrafrom.tfstate` file in my backend. When I attempt to reference it though the file doesn't exist at `my-terraform-resource-name/plan.json` despite `my-terraform-resource-name/name` existing as expected.

Separately I see that the [final comment on #116](https://github.com/ljfranklin/terraform-resource/issues/116#issuecomment-631484926) seems to reference the file being written to the repo resource instead which I'm assuming is a `git` resource of the repo for which CI is being written. Unfortunately it also fails when I try to `cat` `repo/plan.json` (or `repo/path/to/terraform/config/folder/plan.json`).

Do you have any suggestions for how I might fix this? Or for how to debug?

Here is my pipeline code:

```yaml
resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: latest

resources:
  - name: repo
    type: git
    source:
      uri: https://((github-token))@github.com/opendoor-labs/repo.git
  - name: aws-resources
    type: terraform
    source:
      backend_type: s3
      backend_config:
        bucket: opendoor-terraform
        key: services/github-repo-management/terraform.tfstate
        workspace_key_prefix: services/github-repo-management
        region: us-east-1
        access_key: ((aws-access-key-id))
        secret_key: ((aws-secret-access-key))
      vars:
        github_token: ((github-token))
      env_name: github-repo-management

- name: plan-aws-terraform
    plan:
      - get: repo
        trigger: true
      - put: aws-resources
        params:
          plan_only: true
          terraform_source: repo/infra/sox/ci/terraform/github-repo-management
        get_params:
          output_planfile: true
      - task: show-outputs
        config:
          platform: linux
          inputs:
            - name: repo
            - name: aws-resources
          image_resource:
            source:
              repository: bash
            type: docker-image
          run:
            path: bash
            # ref - https://github.com/ljfranklin/terraform-resource/issues/116#issuecomment-631484926
            args:
              - -euc
              - |
                echo "name: $(cat aws-resources/name)"
                echo "plan.json: $(cat aws-resources/plan.json)"
```

**Comment by ljfranklin** [comment]
Try reducing the indent of `get_params` by one level:

```
      - put: aws-resources
        params:
          plan_only: true
          terraform_source: repo/infra/sox/ci/terraform/github-repo-management
        get_params:
          output_planfile: true
```
