### ISSUE TITLE
[feature request] Ability to customize the `name`, `metadata`, `plan.json` filenames (support for across step)

### ISSUE THREAD

**Issue by ari-becker** [ljfranklin/terraform-resource#160]
## Request
Currently, when using `put.get_params.output_planfile: true`, the resource will create a file called `plan.json` with the plan output. Similarly, when running the `put`, files `name` and `metadata` will be created with the `env_name` and Terraform Outputs. None of these filenames can currently be changed - I cannot change `plan.json` to `plan-X.json`, `name` to `name-X`, or `metadata` to `metadata-X`.

To be able to change the name of the files, I would like to be able to define the following options:
* `put.name_filename: <string>`
* `put.metadata_filename: <string>`
* `put.get_params.output_planfile_filename: <string>`

## Why?
Concourse is adding an `across` step that allows for many steps to be executed in parallel across a dynamic range of values. Together with a task that runs `terraform workspace list`, this means that a pipeline can do something like:

```yaml
jobs:
- name: plan-everything
  plan:
  - get: pull-request
    trigger: true
    version: every
  - task: get-terraform-environments
    file: pull-request/concourse/tasks/get-terraform-environments.yaml # runs terraform workspace list, outputs to a JSON list
  - load_var: terraform-environments
    format: json
    file: get-terraform-environments-output/environments.json
  - across:
    - var: environment
      values: ((.:terraform-environments))
      max_in_flight: 4
    do:
    - put: pull-request
      params:
        path: pull-request
        status: pending
        context: ((.:environment))
    - put: terraform
      params:
        terraform_source: pull-request
        env_name: ((.:environment))
        vars:
          environment_picker: ((.:environment))
        plan_only: true
      get_params:
        output_planfile: true
        output_planfile_filename: plan-((.:environment)).json
    - task: prepare-pr-description
      file: pull-request/concourse/tasks/prepare-pr-description.yaml # prepares a description.txt
      vars:
        environment: ((.:environment))
    - put: pull-request
      params:
        path: pull-request
        status: success
        context: ((.:environment))
        description_file: pr-description/((.:name))/description.txt
```

Which allows the Concourse pipeline to dynamically run a `terraform plan` for each and every workspace. But for this to work, the Terraform resource needs to be configured appropriately so that the different instantiations of the resource don't clobber each others' plan / name / metadata files.
