### ISSUE TITLE
Put should support optionally providing native terraform state file

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [ljfranklin/terraform-resource#27]
Currently, the resulting `.tfstate` file resulting from `apply` goes into the S3-compatible backing, but the outputs of the resource only contain this resource's custom JSON format.  This means that I have to write separate scripts for my manual workflow with things like:

```
cat <<EOF > manifest.yml
---
foo: $(terraform --output=PATH_TO_STATE_FILE var_foo)
...
EOF
```

and scripts for my CI workflow like this:

```
cat <<EOF > manifest.yml
---
foo: $(jq .var_foo PATH_TO_JSON_FILE)
...
EOF
```

It would be nice if the tfstate file were also in the output (perhaps as an opt-in feature activated in the `put` parameters) so I could have more unified tooling.

**Comment by ljfranklin** [comment]
This should be good to go, but I'll leave this open until the build goes green

**Comment by ljfranklin** [comment]
@Amit-PivotalLabs works for me, check out the `output_statefile` in the README and give it a spin!

**Comment by Amit-PivotalLabs** [comment]
Can you clarify how this should be used?  Is this correct:

Where I actually apply the terraform config:

```
...
  - put: terraform-state
    params:
      var_file: terraform-vars/terraform-aws.tfvars.yml
      terraform_source: terraforming-aws//infrastructure
      delete_on_failure: true
      env_name: {{env_name}}
    get_params: {output_statefile: true} # I add this line?
...
```

and every subsequent job that consumes the terraform config:

```
    - get: terraform-state
      trigger: true
      passed: [terraform-up]
      output_statefile: true # I also add this line?
```

**Comment by Amit-PivotalLabs** [comment]
Also, assuming I have:

```
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
```

in my pipeline, this will pick up the recently added changes?  Since you have a `nightly` tag on the docker images I'm assuming `latest` gets built on every change to master?
