### ISSUE TITLE
Metadata not available

### ISSUE THREAD

**Issue by vianellod** [ljfranklin/terraform-resource#54]
When running 

```
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: img-sdk
 
- name: terraform
  type: terraform
  source:
    env:
          [bla]
    storage:
      access_key_id: []
      bucket: []
      bucket_path: []
      region_name: []
      secret_access_key: []
    vars: 
         [bla]

- name: src-env
  type: git
  source:
     [some source]

jobs:

  - put: terraform-plan
     resource: terraform
     params:
       terraform_source: src-env/app
       env_name: test-1
       plan_only: true

   - task: show-outputs
     image: img-sdk
     config:
       platform: linux
       inputs:
       - name: terraform-plan
       run:
         path: /bin/sh
         args:
         - -c
         - |
             echo "name: $(cat terraform-plan/name)"
             echo "metadata: $(cat terraform-plan/metadata)"
```

the second task fails with
```
cat: terraform-plan/name: No such file or directory
name: 
cat: terraform-plan/metadata: No such file or directory
metadata: 
```

Intercepting the container I can find the `terraform-plan` directory, but it's empty. The `put` step is successful.

Resource version: latest
Concourse version: 3.10.0

I'm sure this was working before, no idea of what changed in the meantime!
