### ISSUE TITLE
Fails to upload state when using shared credentials file

### ISSUE THREAD

**Issue by minniux** [ljfranklin/terraform-resource#59]
I'm using the [tf backends branch](https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-backends) with S3 backend along with the shared credentials file option.  
My credentials file includes a session token for role with full administration rights.
When applying it can read the state and can apply changes (modify and create resources)  but it fails when trying to upload the state with the following error:
> Failed to save state: failed to upload state: AccessDenied: Access Denied status code: 403

I can confirm session token is not expired, the apply process takes only few seconds, and I can manually using the same token and credentials push the state inside a hijacked container without issues after I get the failure

Let me know if there's something I'm missing or if you need additional information for debugging

**Comment by ljfranklin** [comment]
@minniux my guess is the `backend_config.shared_credentials_file` path might be incorrect. The path should be relative to the `terraform_source` dir I think, so you'd need something like ``backend_config.shared_credentials_file: ../creds/creds.json`. If that doesn't work posting your pipeline config's `source` and `put` sections would help debug further.

**Comment by minniux** [comment]
@ljfranklin thank you for the fast reply, I've tried setting the credentials file relative to `terraform_source` as advised, but still got the same error.

Here are the `source` and `put` sections I'm using:
```
resources:
  - name: example-stack
    type: terraform
    source:
      backend_type: s3
      backend_config:
        bucket: example-bucket
        key: example/main
        region: eu-west-1
        profile: ((AWS_PROFILE_NAME))
        shared_credentials_file: ((CREDENTIALS_FILE))
```
```
  - put: example-stack
    params:
      env_name: staging
      terraform_source: terraform/example-stack
      env:
        AWS_SHARED_CREDENTIALS_FILE: ((CREDENTIALS_FILE))
        AWS_DEFAULT_REGION: eu-west-1
        AWS_PROFILE: ((AWS_PROFILE_NAME))
```

Note that If `put.env` is removed it fails to read the state, and if it's replaced with `source.env` it gives the same behavior to read the state and apply changes without uploading state
