### ISSUE TITLE
Get so i can depend on a destroy

### ISSUE THREAD

**Issue by squeedee** [ljfranklin/terraform-resource#6]
In my pipeline, i want to ensure the stack is removed before redeploying it, i'd like something like:

```yaml
  - name: purge-previous-deployment
    plan:
      - get: environment
        trigger: true
        passed: [claim-environment]
      - get: appdog-ci
      - put: opsman-terraform
        params:
          action: destroy
          env_name: {{environment-name}}
        get_params:
          action: destroy

  - name: create-deployment
    plan:
      - get: opsman-terraform
        trigger: true
        passed: [purge-previous-deployment]
      - get: appdog-ci
      - put: opsman-terraform
        params:
          env_name: {{environment-name}}

```

**Comment by ljfranklin** [comment]
@squeedee After thinking about it for a bit, I think this can be done by adding a "destroyed" field to the [version](https://github.com/ljfranklin/terraform-resource/blob/master/src/terraform-resource/models/version.go):

```go
type Version struct {
	LastModified string `json:"last_modified"`
	EnvName      string `json:"env_name"`
    Destroyed    bool   `json:"destroyed"`
}
```

This way the `get` knows to no-op if it's been told to fetch a destroyed environment, but can still error if it's been told to fetch an environment that never existed or was destroyed out of band.

In the meantime, you can workaround this by doing the destroy and create in the same job:

```yaml
- name: create-deployment
  plan:
    - get: environment
       trigger: true
       passed: [claim-environment]
    - put: opsman-terraform
      params:
        action: destroy
        env_name: {{environment-name}}
      get_params:
        action: destroy
    - get: appdog-ci
    - put: opsman-terraform
      params:
        env_name: {{environment-name}}
```
