### ISSUE TITLE
Boolean `true` becomes a `1` since docker image v0.11.7

### ISSUE THREAD

**Issue by ansd** [ljfranklin/terraform-resource#60]
In our terraform scripts, we have a variable [use_lbaas](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/82ec92b0bf96e42214acfcd02a31796da333559b/ci/terraform/ci/modules/lifecycle/lifecycle.tf#L13-L16) which we set to `false` or `true` (type boolean rather than string) when we want to deactivate/activate lbaas tests. We use this variable [to determine whether to setup loadbalancer resources](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/82ec92b0bf96e42214acfcd02a31796da333559b/ci/terraform/ci/modules/lifecycle/lifecycle.tf#L149). This worked until the new [docker image](https://hub.docker.com/r/ljfranklin/terraform-resource) v0.11.7 has been released.

Since the update of the docker image, when the variable `use_lbaas` is set to `true`, we observe that it becomes a `1` as debugged [here](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/45a6557fb48d9ec1b3e871179e2384f3b426f36f/ci/terraform/ci/lifecycle/lifecycle.tf#L152-L154) so that our [comparison](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/82ec92b0bf96e42214acfcd02a31796da333559b/ci/terraform/ci/modules/lifecycle/lifecycle.tf#L149) doesn't work anymore.

Before https://hub.docker.com/r/ljfranklin/terraform-resource version 0.11.7, the boolean `true` becomes a string  `"true"` in terraform.
Since https://hub.docker.com/r/ljfranklin/terraform-resource version 0.11.7, the boolean `true` becomes a  `1` in terraform.

We guess that's an intended change? Because when we set the variable to string `"true"`, our comparison works again.

**Comment by ljfranklin** [comment]
@ansd can you reproduce the issue outside the resource using `terraform apply`? It'd be helpful to understand where this is an issue with the terraform-resource or terraform itself. I see a couple open issues that sound similar, might be related: https://github.com/hashicorp/terraform/issues/13512 and https://github.com/terraform-providers/terraform-provider-azurerm/issues/1353

**Comment by ansd** [comment]
@ljfranklin, right, I can reproduce this issue outside the resource using `terraform apply`:

```
$ terraform -v
Terraform v0.11.7


$ cat test.tf
variable "use_lbaas" {}

output "use_lbaas" {
  value = "${var.use_lbaas}"
}

$ cat terraform.tfvars
use_lbaas = true

$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

use_lbaas = 1
```

Same output for terraform v0.11.6.

Same output when using ljfranklin/terraform-resource docker image v0.11.7 (which uses terraform v0.11.7):
```
terraform_version | Terraform v0.11.7
use_lbaas | 1
```

But different output when using ljfranklin/terraform-resource docker image v0.11.6 (which uses terraform v0.11.6):
```
terraform_version | Terraform v0.11.6
use_lbaas | true
```

Here is a simple `pipeline.yml` to reproduce:
```
---
jobs:
- name: test-job
  plan:
  - get: tf-git
  - task: show-date
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: [hello-world]
  - put: terraform-validator
    params:
      env_name: testEnv
      terraform_source: tf-git
      vars:
        use_lbaas: true
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.6  # vs 0.11.7
resources:
- name: terraform-validator
  type: terraform
  source:
    storage:
      bucket: <some_bucket>
      bucket_path: <some_path>
      access_key_id: <access_key>
      secret_access_key: <secret_key>
      region_name: <some_region>
- name: tf-git
  type: git
  source:
    uri: https://github.com/ansd/tf-test.git
    branch: master
```
