### ISSUE TITLE
README plan/apply example inaccurate

### ISSUE THREAD

**Issue by ntbrittain** [ljfranklin/terraform-resource#61]
Regarding this example in README

```
- name: terraform-plan
  plan:
    - put: terraform
      params:
        env_name: staging
        plan_only: true
        vars:
          subnet_cidr: 10.0.1.0/24

- name: terraform-apply
  plan:
    - get: terraform
      trigger: false
      passed: [terraform-plan]
    - put: terraform
      params:
        env_name: staging
        plan_run: true
        vars:
          subnet_cidr: 10.0.1.0/24
```

This suggests that the same vars must be passed into both the plan and apply steps. Since the generated plan should include all the necessary data I believe this is unnecessary. As I would expect, the apply method in the client doesn't call out to c.writeVarFile() when PlanRun is true. https://github.com/ljfranklin/terraform-resource/blob/a01dca68ad25cce6fb7e7e0147019874b04d19e8/src/terraform-resource/terraform/client.go#L44
