### ISSUE TITLE
Get so I can read state

### ISSUE THREAD

**Issue by squeedee** [ljfranklin/terraform-resource#7]
I want to be able to specify Get to read the metadata from my terraform template output as dependable data for further scripts, for example, configuring a parent DNS server. Right now I must use the AWS CLI inside a task to obtain accurate data from the tfstate file, as using the s3-resource wont work, thinking its current version is accurate when it may not be.

Happy to walk you through this with a pairing session.

**Comment by ljfranklin** [comment]
@squeedee The `get` already grabs your terraform outputs unless I misunderstood your question. You should be able to do this:

```yaml
- name: get-env
  plan:
    - get: terraform
    - task: test
      # task can reads outputs from `terraform/metadata`
```

The line from the README is maybe misleading: "This resource should always be used with the put action rather than a get". Always doing a `put` ensures that anything that was changed out of band gets put back in line with the template just before the test runs, but having a terraform `put` then trigger multiple jobs via terraform `get` is a fine thing to do.

Let me know if I misunderstood your question.
