### ISSUE TITLE
migrated_from_storage does not appear to be pulling original state file when running plan

### ISSUE THREAD

**Issue by ebrusseau** [ljfranklin/terraform-resource#81]
I have configured the Backend Migration as described (with corrected key name), and yet when we run the plan step in our pipeline, Terraform wants to create all resources.

The expected behavior would be that it should read the original state file from the original bucket/path (now in migrated_from_storage), runs plan against this original state file to come up with the work and persist the plan in the backend. It appears to run the plan, but again does not utilize the existing state file.

Here's what my resource looks like:

```yaml
- name: terraform-iaas
  type: terraform
  source:
    migrated_from_storage:
      bucket: ((terraform.storage.bucket))
      bucket_path: ((terraform.vars.env_name))/((terraform.storage.bucket_path_iaas))
      access_key_id: ((terraform.storage.access_key_id))
      secret_access_key: ((terraform.storage.secret_access_key))
      region_name: ((terraform.storage.region_name))
    backend_type: s3
    backend_config:
      bucket: ((terraform.storage.bucket))
      workspace_key_prefix: ((terraform.storage.bucket_path_iaas))
      key: ((terraform.vars.env_name)).tfstate
      region: ((terraform.storage.region_name))
      access_key: ((terraform.storage.access_key_id))
      secret_key: ((terraform.storage.secret_access_key))
    vars: ((terraform.vars))
```

.. and the put from job:

```yaml 
 - put: terraform-iaas
    params:
      env_name: ((terraform.vars.env_name))
      terraform_source: ((terraform.source_folder))
      override_files: ((terraform.override_files))
      plan_only: true
```

What am I doing wrong? With 0.11.11 of the Docker image, this works fine (with storage: instead of migrated_from_storage, of course)...
