### ISSUE TITLE
Plugin reinitialization required on plan_run with beta-backend image

### ISSUE THREAD

**Issue by cludden** [ljfranklin/terraform-resource#83]
First off, let me just say thank you for all the work on this project, especially to support workspaces! Anyways, here's my issue:

I'm trialing the plan_only support with backends that was recently added. the plan_only phase completes successfully, but when I try to apply with plan_run enabled, I'm getting:

```
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.random: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".
```

**Comment by ljfranklin** [comment]
@cludden interesting, let's try to pin down exactly what code path you're hitting. Are you using `migrated_from_storage` feature in your config? Are you using `module_override_files` or `override_files`?

**Comment by ljfranklin** [comment]
@cludden also you should switch back to the `latest` image now that all the workspace stuff has been merged into `master`.

**Comment by cludden** [comment]
@ljfranklin good to know! also, I'm not using `migrated_from_storage`, `module_override_files`, `override_files`. here is my config:
resource:
```
{
  name: 'terraform',
  type: 'terraform',
  source: {
    terraform_source: 'git/terraform',
    backend_type: 's3',
    backend_config: {
      bucket: '<BUCKET>',
      dynamodb_table: '<TABLE>',
      key: '<KEY>',
      workspace_key_prefix: '<PREFIX>,
      region: '<REGION>',
      encrypt: true,
      access_key: '((concourse-access-key-id))',
      secret_key: '((concourse-secret-access-key))',
    },
    private_key: '((git-private-key))',
  },
},
```

step:
```
{
  put: 'terraform',
  get_params: {
    action: vars.action,
  },
  params: {
    terraform_source: 'git/terraform',
    env_name: env.name,
    action: vars.action,
    vars: vars,
  },
},
```

**Comment by ljfranklin** [comment]
@cludden A couple things to double-check:
- The first CI job has `put.params.plan_only: true`
- The second CI job has `put.params.plan_run: true`
- The second CI job has a valid `terraform_source` set and the given directory was fetched via a `get`
- Ensure that the directory passed as `terraform_source` matches the directory used to generate the plan

Nothing is jumping out with as wrong with the resource, but could be some subtle interaction I'm not seeing.

**Comment by cludden** [comment]
for the second ci job, should there also be a preceding `get: terraform` step with a .`passed` attribute that includes the first ci job?

**Comment by cludden** [comment]
ok, so I upgraded to the latest version and everything is working now. I can't say for sure what changed, I had switched back to using the old approach over the last few days, but everything is working as expected now. I'll reopen if I encounter the same behavior as before. Thanks for your help, and again, great work!

**Comment by cludden** [comment]
Ok, I just ran in to this again, with the latest image, after adding a new provider + resource to an existing terraform module. here's the relevant pieces from the pipeline
```yml
groups: []
resources:
- name: source
  webhook_token: ((webhook-token))
  type: git
  source:
    branch: master
    private_key: ((git-private-key))
    uri: git@github.com:XXXXXXXXXXX.git
- name: terraform
  type: terraform
  source:
    backend_config:
      access_key: ((concourse-access-key-id))
      bucket: XXXXXXXXXXX
      dynamodb_table: XXXXXXXXXXX
      encrypt: true
      key: XXXXXXXXXXX
      region: XXXXXXXXXXX
      secret_key: ((concourse-secret-access-key))
      workspace_key_prefix: XXXXXXXXXXX
    backend_type: s3
    private_key: ((git-private-key))
    terraform_source: source/terraform
resource_types:
- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
jobs:
- name: plan
  serial: true
  build_logs_to_retain: 100
  plan:
  - get: source
    passed:
    - set-pipeline
    trigger: true
  - aggregate:
    - get: jsonnet-lib
    - get: vault
  - task: copy-terraform-secrets
  - task: flyrc
  - task: render-terraform
  - put: terraform
    params:
      action: apply
      env: {}
      env_name: XXXXXXXXXXX
      plan_only: true
      terraform_source: source/terraform
      vars: {}
    get_params:
      action: apply
- name: apply
  serial: true
  build_logs_to_retain: 100
  plan:
  - get: source
    passed:
    - plan
  - put: terraform
    params:
      action: apply
      env: {}
      env_name: XXXXXXXXXXX
      plan_run: true
      terraform_source: source/terraform
      vars: {}
    get_params:
      action: apply
```

the plan step passes with:
```shell
▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ Terraform Plan ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼
Plan: 3 to add, 0 to change, 0 to destroy.
▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Plan ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
Successfully Ran Terraform Plan!
```

the apply step fails with:
```shell
▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ Terraform Apply ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error occurred:
	* provider.random: no suitable version installed
  version requirements: "(any version)"
  versions installed: none



Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".


Error: error satisfying plugin requirements


▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Apply ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
Failed To Run Terraform Apply!
2019/05/28 19:20:30 Apply Error: Failed to run Terraform command: exit status 1
```
