### ISSUE TITLE
Support for older tags

### ISSUE THREAD

**Issue by mdharamadas1** [ljfranklin/terraform-resource#89]
I'm trying to use tag `0.11.3` (because we have requirement to use Terraform v0.11.3) but looks like there is no documentation on how to use that specific version of resource. I even can't figure out what level of support is available for older tags.  
README says `Specific versions of Terraform, e.g. ljfranklin/terraform-resource:0.7.7.` but I doubt its only the terraform version is different? 

Can someone please clarify? TIA

**Comment by aegershman** [comment]
I hope this helps:

List of docker tags which correspond to the version of terraform used:

https://hub.docker.com/r/ljfranklin/terraform-resource/tags

Usage is that instead of this:

```yml
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest
```

where `tag:` is `latest`, you'd want to the tag to be the Docker tag corresponding to the version you want, e.g., like this:

```yml
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.3
```

does that make sense?
