### ISSUE TITLE
retry after a time

### ISSUE THREAD

**Issue by squeedee** [ljfranklin/terraform-resource#9]
Much like cloudformation before it, I usually find terraform needs to take a few 'stabs' at completing an update. It seems like it's more of a problem for us in AWS us-east region than for people using us-west.

Are you amenable to a retry and a time-between-retry parameter?

**Comment by ljfranklin** [comment]
@squeedee I'd recommend adding an [attempts](http://concourse.ci/retry-step.html) field to your `put` step:

```yaml
- name: get-env
  plan:
    - put: terraform
      attempts: 5
      params: ...
```

I'm not sure how long Concourse delays between tries, but I'm guessing this will solve your problem.

You could also open an issue with Terraform describing the problem you're seeing, e.g. Terraform intermittently fails to destroy VPC when using network ACL.
