### ISSUE TITLE
Terraform init error while using tag 0.11.3

### ISSUE THREAD

**Issue by mdharamadas1** [ljfranklin/terraform-resource#90]
I'm getting following error while using `0.11.3` tagged resource:
`Backend reinitialization required. Please run "terraform init"`

I know latest version does call init implicitly for every command but how does `init` work for 0.11.3? I don't see anything in that version of README.

**Comment by ljfranklin** [comment]
I only added support for Terraform backends in a slightly later version of the resource. If look at the README at [this commit](https://github.com/ljfranklin/terraform-resource/commit/3f502f499dea224bab846a2b1fb54f88b3eec50d#diff-9f24394d99c53dc951e2f3990bfb711f) you can see it still uses the previous custom S3 client to persist the statefile (the `storage` key rather than `backend_config`). Either you can configure your pipeline with the `storage` key as the README shows at that point, or build a custom image as I suggested [here](https://github.com/ljfranklin/terraform-resource/issues/89#issuecomment-499725484).

**Comment by mdharamadas1** [comment]
Sorry for not including the details earlier. I did configure S3 as per the README (as below) and still get that error.
```
- name: terraform
  type: terraform
  source:
    storage:
      driver: s3
      bucket: bucket_name
      bucket_path: path/
      region_name: eu-west-2
      access_key_id: ((aws_access_key))
      secret_access_key: ((aws_secret_key))
      env:
        AWS_ACCESS_KEY_ID: ((aws_access_key))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_key))
```
