### ISSUE TITLE
"Error running `workspace list`" with no output

### ISSUE THREAD

**Issue by DanielJonesEB** [ljfranklin/terraform-resource#97]
I've got no idea what the problem is here... Using 0.12.6. Ran some Terraform through the resource once, and it worked. Running an update through and getting this:

```
▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ Terraform Apply ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼
▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ Terraform Apply ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲
Failed To Run Terraform Apply!
2019/08/19 11:33:21 Apply Error: Error running `workspace list`: exit status 1, Output: 
```

Here's the config in the pipeline, all of which have sensible values:
```
- name: bosh-tf
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      prefix: bosh
      <<: &tf-backend-config
        bucket: ((project_id))
        credentials: ((gcp_credentials_json))
    env:
      GOOGLE_CLOUD_KEYFILE_JSON: ((gcp_credentials_json))
      GOOGLE_PROJECT: ((project_id))
      GOOGLE_REGION: ((region))
      GOOGLE_ZONE: ((zone))
```

and the `put`:
```
- name: bosh-tf
  serial: true
  plan:
  - get: cfvk8s
    trigger: true
    passed: [setup-ci]
  - put: bosh-tf
    attempts: 2
    params:
      terraform_source: cfvk8s/k8s/tf/bosh/
      env_name: default
      vars:
        bucket_location: ((bucket_location))
        project_id: ((project_id))
```

Have I missed something obvious?
