### ISSUE TITLE
Destroy specific resource

### ISSUE THREAD

**Issue by Lewiscowles1986** [ljfranklin/terraform-resource#99]
I'm trying to use this to destroy a resource.

```
  - put: aws-sqs
    get_params:
      action: destroy module.app_name_queue
    params:
      <<: *aws-sqs-params
      action: destroy module.app_name_queue
```

This is my attempt to follow https://www.terraform.io/docs/commands/state/rm.html#example-remove-a-module
